#! /bin/sh
# ----------------------------------------------------
# file:   ${BUILDS}/clean
# author: SirJls - http://sjorssparreboom.nl
# ----------------------------------------------------

find . -name "*src*" -type d -exec rm -rf {} \;
find . -name "*pkg*" -type d -exec rm -rf {} \;
find . -name "*tar*" -type f -delete -print0
find . -name "*.o" -type f -delete -print0
find . -name "*.c" -type f -delete -print0

maps=($(find $PWD -maxdepth 1 -name "*" -type d | sed 's/.*\///g'))

skip_first=1
for elem in "${maps[@]}"; do
  (( skip_first != 1 )) && rm -rf "${PWD}/${elem}/${elem}"
  (( skip_first++ ))
done
